baseURL = 'http://beagle4ce.github.io/'
languageCode = 'en-us'
title = "Beagle's Cottage"
theme = "ananke"


DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
summaryLength = 3


[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags" # use tags
  category = "categories"
  series = "series"

[markup.tableOfContents]
  startLevel = 1
  endLevel = 2
  ordered = true

[markup.highlight]
  # Chroma Style Gallery: https://xyproto.github.io/splash/docs/
  style = "monokai"
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  # hl_Lines = ''
  # hl_inline = false
  # lineAnchors = ''
  # lineNoStart = 1
  # tabWidth = 4
  lineNos = true
  lineNumbersInTable = false
  noClasses = true
  noHl = false

[params]
  text_color = "black"
  author = "Beagle"
  favicon = "images/avatar_betacat_07.png"
  # Online image editor: https://www.fotor.com
  site_logo = "images/avatar_betacat_07.png"
  # body_class里设置了字体class,字体颜色class和背景class
  body_classes = "avenir near-black bg-washed-yellow"
  # description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 6

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/beagle4ce"
  label = "Github"

[[menu.main]]
  name = "Index"
  weight = 1
  url = "/"

[[menu.main]]
  identifier = "articles"
  name = "Articles"
  weight = 2
  url = "/articles/"

[[menu.main]]
  identifier = "tags"
  name = "Tag"
  weight = 3
  url = "/tags/"

[[menu.main]]
  identifier = "categories"
  name = "Category"
  weight = 4
  url = "/categories/"

[[menu.main]]
  identifier = "series"
  name = "Series"
  weight = 5
  url = "/series/"

[[menu.main]]
  identifier = "about"
  name = "About"
  weight = 100
  url = "/about/"

[[menu.main]]
  identifier = "ides"
  name = "IDEs"
  weight = 1
  parent = "articles"
  url = "/articles/ides/"

