baseURL = 'http://beagle4ce.github.io/'
languageCode = 'en-us'
title = "Beagle's Cottage"
theme = "ananke"

DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Beagle"
  favicon = "images/avatar_betacat_07.png"
  # Online image editor: https://www.fotor.com
  site_logo = "images/avatar_betacat_07.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 6

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/beagle4ce"

[[menu.main]]
  name = "Index"
  weight = 1
  url = "/"

[[menu.main]]
  identifier = "articles"
  name = "Articles"
  weight = 2
  url = "/articles/"

[[menu.main]]
  identifier = "about"
  name = "About"
  weight = 3
  url = "/about/"

